name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update this repo's README

    steps:
      - uses: actions/checkout@v3

      # # Recent activity
      # - uses: jamesgeorge007/github-activity-readme@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Recent blog posts 
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://fredrikaverpil.github.io/feed_rss_created.xml"
